### ISSUE TITLE
Galaxy model taking over point source in a galaxy+point source blend

### ISSUE THREAD

**Issue by charlotteaward** [pmelchior/scarlet2#15]
I've been coming across some tricky issues when trying to deblend a galaxy with a bright point source and wanted to crowd source some ideas. This is the scarlet1 model, which look pretty good when rendered but has more noise than usual around the point source in the residuals, which presumably arises because it's so bright. 

![image](https://github.com/pmelchior/scarlet2/assets/31629003/9448b6c5-398b-444b-ba8c-6a3aa6f43559)

When I model this in Scarlet2, source 0 (a normal source with the HSC prior) tries to model the point source, while source 1 (a point source) has its best-fit flux set to 0. Then the actual galaxy is poorly modeled:

![image](https://github.com/pmelchior/scarlet2/assets/31629003/7d86e566-b4cf-463b-93e1-c86b7488d4ec)
![image](https://github.com/pmelchior/scarlet2/assets/31629003/de2c63a1-19c3-40da-a21f-cf55a42fe9cf)

I tried making a smaller box size just to see what happens when the galaxy doesn’t completely overlap the point source, and things go terribly wrong in a way that I can’t quite understand:

![image](https://github.com/pmelchior/scarlet2/assets/31629003/92f91360-e38f-4df7-a372-3e7f92537688)

Is there a good way to make sure the galaxy model doesn't use its flexibility to model the bright point source? There is no variability in this case - just 3 images in different bands.

**Comment by SampsonML** [comment]
Hi Charlotte, I have no experimented much with point sources but am no looking at some ground trotting for how well scarlet 2 performs in highly blended environments.  I did somewhat of a recreation of this setup, here I have a single very bright (mag ~23) central source with other sources well inside its flux. I found the results are quite sensitive to the fitting parameters, and in the case of a totally hidden blend, the positive constant is needed for decent behavior right now, while we are working with flat, potentially non-ideal step sizes. 


Here is an example, with positive constraints and HSC prior

![scar2_posi_all](https://github.com/pmelchior/scarlet2/assets/44228257/9158af21-5433-498f-90b9-7a75bad52131)

Now same example no constraints

![scar2_no_all](https://github.com/pmelchior/scarlet2/assets/44228257/76f83b39-e095-4329-b33a-13601923d7d6)


This really, is down to convergence issues, with heavily blended images the step sizes need to reduce otherwise the convergence will just fall off a cliff and we begin to go completely outside the domain of the prior. The positive constraints seem to significantly help stabilize this for now.


However, if you are using the positive constraints and still getting this, then an option is to really start turning down the step size (maybe 1e-4 or smaller even) and see what happens?

**Comment by SampsonML** [comment]
Also, if possible maybe try avoiding point sources totally and see how scarlet2 does

**Comment by pmelchior** [comment]
Step sizes could be an issue here, for sure.

Looking at another plot Charlotte showed, it looks like there could also be a sky subtraction issue because the residuals show the outline of source 0. If that's the case, convergence will be particularly hard for all sources.

This might argue for adding a `FlatSource` component into the mix, which basically has
```python
def __call__(self):
    return jnp.ones(self.bbox.shape)[None,:,:] * self.spectrum[:, None, None]
```

**Comment by SampsonML** [comment]
Relative step sizes and the updated temperature change in #23 potentially fix this, let me know if issues still persist.

**Comment by pmelchior** [comment]
@charlotteaward Can this issue be closed?

**Comment by charlotteaward** [comment]
Yes, it's no longer a problem!

**Comment by pmelchior** [comment]
Then close it, please

**Comment by charlotteaward** [comment]
Resolved with relative step sizes.
