### ISSUE TITLE
hdf5 save routine

### ISSUE THREAD

**Issue by SampsonML** [pmelchior/scarlet2#82]
I have added a skeleton for a saving routine for scarlet2 to save to hdf5. See the ongoing testing here (https://github.com/pmelchior/scarlet2/blob/hdf5_outputs/tests/test_save_output.py) 

The save routine is here (https://github.com/pmelchior/scarlet2/blob/hdf5_outputs/scarlet2/io.py)

We should decide a few things, we should save

1.  Each scene ID 
2.  The psf, and weights of the frame
3. The observation in all bands
4. The raw arrays of each deblended scene morphology
5. The spectrum for each deblended source 
6. The center coords of each source in pixel units

We can (with adaptions) save

1.  The scene model itself, and all its attached params

Please comment thoughts and things to include

**Comment by pmelchior** [comment]
OK, this is a good start. I would not save the inputs to scarlet, they are already in another HDF file (that's what #81 is about). The main problem I see with this one is that `save_h5py` only saves `morphology` and `spectrum` arrays, which is not a full description of the sources. Even if we stick with the default parameterization (as opposed to, say, `SersicMorphology`), we'd have to start the bounding boxes as well.

The larger issue is that we can't reconstruct the sources from the contents of the file. This may be OK if we only ever wanted to measure something from the models, but we couldn't e.g. refit a scene with one more component because the scene requires more information than is currently stored. This is why we chose to pickle the entire scene in scarlet1, which means we stored the source classes and all of their data. See [this](https://pmelchior.github.io/scarlet/0-quickstart.html#Save-and-Re-Use-Model) example.

Can you try to pickle the scene to a file and check how much memory it requires. Then try equinox's serialization [functions](https://docs.kidger.site/equinox/api/serialisation/#equinox.tree_serialise_leaves). If we can do those successfully with low overhead, it should be possible to pipe them into HDF5.

**Comment by SampsonML** [comment]
Hmm I see, ok will work to store the full scene model.

**Comment by pmelchior** [comment]
closed with #83
